[[servers]]
host = "10.0.0.5"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = false

bind_dn = "cn=admin,dc=inter,dc=lan"
bind_password = "pass"
search_filter = "(uid=%s)"
group_search_base_dns = ["cn=miners,ou=Groups,dc=inter,dc=lan"]
group_search_filter_user_attribute = "uid"
timeout = 3

group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"

search_base_dns = ["dc=inter,dc=lan"]


[server.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"


[[servers.group_mappings]]
group_dn = "*"
org_role = "Admin"
grafana_admin= true
